import Head from 'next/head'
import Layout from '../components/Layout'
import Section from '../components/Section'

export default function Blog() {
  return (
    <>
      <Head>
        <title>Coobyk: Blog</title>
        <meta name="description" content="Blog of Coobyk" />
        <link rel="icon" href="/images/coobyk.svg" />
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet" />
      </Head>
      <div className="bg-color-background text-color-text min-h-screen">
        <Layout>
          <main className="p-8 justify-center align-center flex flex-col gap-5">
            <div className="inline-flex gap-10 items-center h-fit self-center mt-20">
              <img src="/images/coobyk.svg" alt="Profile Picture, a big cube" className="max-h-96 hover:scale-125 transition-all ease duration-300 z-20 shadow-2xl" style={{clipPath: 'polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%)'}} />
              <div className="text-center mt-4">
                <div className="flex justify-center font-mono text-color-primary text-9xl font-bold">
                  {[...'Blog'].map((char, i) => (
                    <span key={i} className="hover:scale-150 transition-all ease origin-bottom hover:text-shadow text-shadow-color-primary text-shadow-blur">{char}</span>
                  ))}
                </div>
                <h3 className="text-color-secondary transition-all font-mono text-xl mt-2 hover:text-shadow text-shadow-color-secondary text-shadow-blur-5">"My blog where I post things"</h3>
              </div>
            </div>
            <Section title="Blog">
              <h1 className="text-3xl font-bold font-mono text-color-secondary">This blog will be generated by <a className="text-color-accent" href="https://github.com/Coobyk/Avocado" target="_blank" rel="noopener noreferrer">Avocado</a>. Please check <a className="text-color-accent" href="https://github.com/Coobyk/Avocado" target="_blank" rel="noopener noreferrer">Avocado</a>'s repository to see when it will be ready.</h1>
            </Section>
          </main>
        </Layout>
      </div>
    </>
  )
}
